### ISSUE TITLE
Have you solved the problem yet

### ISSUE THREAD

**Issue by SunSeekerX** [thawri1/MyStaggeredListSample#1]
I have the same problem. but I can't solve it

**Comment by thawri1** [comment]
hi @SunSeekerX .
sorry for the late answer.
I think this problem is solved using this answer:
https://stackoverflow.com/a/65596421/10109704

**Comment by SunSeekerX** [comment]
> 

Still the same problem. Fragment > ViewPage2 > Fragment > RecycleView with StaggeredGridLayoutManager

**Comment by SunSeekerX** [comment]
> hi @SunSeekerX . sorry for the late answer. I think this problem is solved using this answer: https://stackoverflow.com/a/65596421/10109704

It's not work for me.
